Feature/mainpage
wecode-bootcamp-korea/39-1st-jojoclub-backend pull request #2
Opened 2022-11-16 02:49 UTC by julius1231

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 제품 조회 기능 구현

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

2. 제품 데이터 처리
- 제품명(한글,영어), 용량별가격, 이미지URL, 용량

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 레이어드 페턴을 구현해 볼 수 있었다. (해당 기능이 없어도 모든 레이어를 통과해야함)
- 파일시스템 모듈을 활용하여 csv파일 데이터를 입력해야 하나 이를 활용하지 못함(tablePluse 사용)

## :: 기타 질문 및 특이 사항
- tablePluse를 사용했는데 파일시스템 모듈을 사용하지 못햇습니다.. 추후에 반영해 보도록 하겠습니다.

2022-11-16 05:39 UTC, bigfanoftim commented
> tablePluse를 사용했는데 파일시스템 모듈을 사용하지 못햇습니다.. 추후에 반영해 보도록 하겠습니다.

괜찮습니다! 어찌 되었든 개발을 올바르게 진행할 수만 있다면 뭐든 좋습니다~!

2022-11-16 05:48 UTC, bigfanoftim requested changes

2022-11-16 05:48 UTC, bigfanoftim commented on src/controllers/product.controller.js
> +    res.status(200).json(await productService());
```suggestion
const productService = require("../services/product.service");

const getProducts = async (req, res) => {
  try {
    res.status(200).json(await productService.getProducts());
```

다음과 같이 서비스 모듈을 통으로 불러와 활용할 수 있도록 하면 좋을 것 같아요~

2022-11-16 05:48 UTC, bigfanoftim commented on src/services/product.service.js
> +};
```suggestion
const productDao = require("../models/product.dao");

const getProducts = async () => {
  return await productDao.getProducts();
};
```

2022-11-16 05:48 UTC, bigfanoftim commented on src/models/product.dao.js
> +    ORDER BY created_at limit 7;
```suggestion
```
ORDER BY와 LIMIT을 고정하게 되면 사용자에 입맛에 맞게 정렬 및 개수 보기 설정이 불가능해집니다. 설령 지금 기획에 없다 하더라도 무조건 있어야 하는 기능이므로 앞으로의 확장성을 고려하여 클라이언트로 부터 해당 값들을 전달받고 처리해 주세요!

2022-11-16 05:48 UTC, bigfanoftim commented
- PR 타이틀 혹은 설명 부분을 보다 상세하게 작성해 주세요.
- 구현 사항을 자세히 적으면서 본인이 어떻게 구현했는지 스스로 이해도를 점검해 볼 수 있으며, 나중에 내가 어떤 고민을 하고 어떻게 문제를 해결했는지 회고해 볼 수 있는 좋은 자산이 됩니다.

2022-11-16 14:01 UTC, julius1231 commented
![Screen Shot 2022-11-16 at 10 48 56 PM](https://user-images.githubusercontent.com/100187797/202197862-a4b1eb52-690a-4ff6-a8ed-d29e71f7de70.png)
멘토님 질문있습니다!
공부할겸 다음과 같이 테이블을 새로 구성해봤습니다. 이런식으로 구현할 경우 제품에 필요한 모든 정보를 Inner join을 통해 한 번에 보여줄 수 있을것 같은데 어떻게 생각하시나요?
(해당 database 스키마는 최종본이 아닙니다. 제품과 관련된 테이블만 구현했고 user, order 등 다른 테이블은 아직 구현하지 않은 상태입니다.)

2022-11-17 02:23 UTC, bigfanoftim commented
> ![Screen Shot 2022-11-16 at 10 48 56 PM](https://user-images.githubusercontent.com/100187797/202197862-a4b1eb52-690a-4ff6-a8ed-d29e71f7de70.png) 멘토님 질문있습니다! 공부할겸 다음과 같이 테이블을 새로 구성해봤습니다. 이런식으로 구현할 경우 제품에 필요한 모든 정보를 Inner join을 통해 한 번에 보여줄 수 있을것 같은데 어떻게 생각하시나요? (해당 database 스키마는 최종본이 아닙니다. 제품과 관련된 테이블만 구현했고 user, order 등 다른 테이블은 아직 구현하지 않은 상태입니다.)

잘 만드신 내용을 왜 다시 롤백했는지 모르겠습니다만 size가 여러개인 것은 테이블이 아니라 데이터여야 합니다.

2022-11-17 12:48 UTC, julius1231 commented on src/models/product.dao.js
> +    ORDER BY created_at limit 7;
ORDER By 와 LIMIT을 뺴라는 말씀이신가요? 아니면 아래와 같이 함수를 받아 올 수 있도록 구현하라는 말씀이신가요?

```
ORDER BY ? LIMIT ?;
`,
[orderByValue, limitValue]
```

2022-11-17 12:49 UTC, julius1231 commented on src/controllers/product.controller.js
> +    res.status(200).json(await productService());
반영 완료했습니다.

2022-11-17 12:49 UTC, julius1231 commented on src/services/product.service.js
> +};
반영했습니다~

2022-11-18 03:07 UTC, bigfanoftim requested changes
1. 회원가입, 로그인
2. 제품 리스트 조회

위와 같이 PR 나눠주세요~ 아마 2번 PR에서 계속 블로커가 될 것 으로 예상됩니다.

2022-11-21 01:38 UTC, bigfanoftim commented
<img width="573" alt="image" src="https://user-images.githubusercontent.com/62135254/202942822-75f3e61e-b145-4931-b66d-20a8dc659429.png">
피드백 확인 후 재적용 해주세요~

2022-11-21 06:59 UTC, merged